# Generated by Django 2.2.16 on 2022-08-14 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220813_1708'),
        ('users', '0002_alter_user_first_name'),
    ]

    operations = [
    ]
