# Generated by Django 2.2.16 on 2022-08-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_comment_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='mark',
            new_name='score',
        ),
    ]
