# Generated by Django 2.2.16 on 2022-08-18 11:50

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220816_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[reviews.validators.validate_actual_year], verbose_name='Год выпуска'),
        ),
    ]
